[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--legacy-peer-deps"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle custom 404 page
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404 